name: Docker Image CI

on:
  push:
    branches: [ develop ]
    paths:
      - "DataProvider"
      - "Common"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x

    - name: Build x64 Version of Application
      run: dotnet publish DataProvider.csproj -o ./artifacts/DataProviderx64 -r linux-x64
      working-directory: DataProvider

    - name: Build ARM64 Version of Application
      run: dotnet publish DataProvider.csproj -o ./artifacts/DataProviderarm64 -r linux-arm64
      working-directory: DataProvider

    - name: Build ARM32 Version of Application
      run: dotnet publish DataProvider.csproj -o ./artifacts/DataProviderarm64 -r linux-arm
      working-directory: DataProvider
